### ISSUE TITLE
Проблема при создании превью в FF

### ISSUE THREAD

**Issue by MaZaTroN** [mailru/FileAPI#200]
Добрый день. Я столкнулся с такой проблемой:
В Firefox при создании превью на определенном изображении, создается пустой прозрачный файл. Путем экспериментов появилась некая зависимость - если ширина создаваемого превью больше в ~1.3 раза, только тогда возникает эта проблема. Например:
```
w: 260
h: 200
Результат:  все ок

w: 270  (и больше)
h: 200
Результат: пустой файл
```

или для сравнения
```
w: 870
h: 660
Результат: все ок

w: 880 (и больше)
h: 660
Результат: пустой файл
```
В chrom'e, IE 11 - ок.

Для создания превью используется код:
```
FileAPI.Image(file).preview(width, height);
```
Изображение на котором воспроизводится проблема:
https://dl.dropboxusercontent.com/u/13181343/anypics.ru_61482.jpg

**Comment by arusakov** [comment]
Я понимаю, что дело было давно, но проблема еще актуальна или как? Я воспроизвести не смог.

**Comment by MaZaTroN** [comment]
Ой. Забыл закрыть.
Проблема в ФФ. Он не умеет обрабатывать изображения у которых разрешение по любой из сторон >8192 пикселей ( с включенным софтовым ускорением кажись)
