### ISSUE TITLE
Uncaught TypeError: Cannot read property 'wrap' of undefined

### ISSUE THREAD

**Issue by Folour** [mailru/FileAPI#203]
В версии 2.1.0 из ветки dev в хроме ошибка, ругается на строку 4472
https://github.com/mailru/FileAPI/blob/dev/dist/FileAPI.js#L4472

**Comment by sahlouls** [comment]
Hi,
Is this error solved already ?

**Comment by RubaXa** [comment]
dev-branch will never be accepted and is outdated.
