### ISSUE TITLE
Node.JS Server for tests.

### ISSUE THREAD

**Issue by RubaXa** [mailru/FileAPI#276]

**Comment by arusakov** [comment]
А что собственно нужно?
Иметь простенький сервак на ноде, который умеет все тоже, что и php-ные скрипты из папочки server?

**Comment by RubaXa** [comment]
@arusakov Да, именно это и нужно. Даже Express проще поднять, просто рук нет, чтобы сделать.

**Comment by RubaXa** [comment]
@arusakov завел ветку [node-testing](https://github.com/mailru/FileAPI/tree/node-testing)
Попытался в ней поднять хоть часть тестов, но сдался, node не моя тема ;]

**Основные проблемы**
 - https://github.com/mailru/FileAPI/blob/node-testing/node/server.js#L35 — нужно отфильтровать только картинки
 - https://github.com/mailru/FileAPI/blob/node-testing/node/file-api.js#L28-L30 — как-то надол распарсить скрутуру в массивы и объекты, сейчас работает не равильно

**Comment by arusakov** [comment]
@RubaXa звучит не сложно :)

**Comment by RubaXa** [comment]
@arusakov Это миниму, что нужно сделать ;]
Ещё я не успел это подружить с `grunt tests` поэтому запускал руками и тестировал через браузер ;]

Вот ещё, а почему ты используешь node-canvas? Разве там нет какого-нибудь биндинга GD или ImageMagic?

**Comment by arusakov** [comment]
@RubaXa
node-canvas - знаком мне и его можно запустить под любой OS, хотя и в это в интернетах не верят, но на Win и на Mac OS X у меня лично работает. Насчет GD или IM тоже пишут, что все плохо, но собственного опыта установки и работы с ними из node.js не имею.

**Comment by RubaXa** [comment]
@arusakov понятно, беда-беда ;] ну ладно.

**Comment by RubaXa** [comment]
@arusakov На чем мы там остановились, сейчас вроде часть тестов заработала, но что-то осталось.

**Comment by arusakov** [comment]
@RubaXa да закончили на том, что я починил "основные моменты", а в мастере не все тесты проходили. В принципе можно двигаться дальше.

**Comment by RubaXa** [comment]
@arusakov давай тогда выключим тесты, которые валятся и заведем задачи на них, чтобы хоть не висело `build fail`.

Займешь?
