### ISSUE TITLE
Failed to get preview in IE < 10

### ISSUE THREAD

**Issue by skotchio** [mailru/FileAPI#284]
I'm trying to get preview from images like the following:

    FileAPI.event.on('input', "change", function (e){
         FileAPI.each(FileAPI.getFiles(e), function (file) {           
                FileAPI.Image(file).preview(50).get(function (err, img) {
                    if (err || !img) {return;}

                    // [error] I'll never be here because of err is `true` and img is `undefined` 
                    $container.append(img) 
                });
         }, this);
    });

I'm trying to run the code above in other browser (Crhome) and it works well. I tried debug through stack trace and found that the problem in the following line https://github.com/mailru/FileAPI/blob/master/dist/FileAPI.js#L705. In IE<10 uploading image is not a File object actually.

I'm using the latest FileAPI 2.0.9

**Comment by RubaXa** [comment]
Please check:
1. `Flash` support (http://mailru.github.io/FileAPI/#en/FileAPI.support.flash)
2. `js-fileapi-wrapper` required class name (http://mailru.github.io/FileAPI/#en/buttons.examples)
3. If that does did not help, turn on `FileAPI.debug = true` and see `Console`.

**Comment by skotchio** [comment]
@RubaXa thanks. My error was in missing `js-fileapi-wrapper` class. I have the last question and let me ask here. Is it possible to always get `IMG` HTML element ?

    FileAPI.Image(file).preview(50).get(function (err, img) {
              // need always get IMG html element
    });

**Comment by RubaXa** [comment]
No, it can be
 - html5: `canvas` (html5)
 - flash: `img` or `div > embed`

**Comment by skotchio** [comment]
@RubaXa thanks again. I'm a little don't understand why we must to provide `js-fileapi-wrapper` Is it really necessary?

**Comment by RubaXa** [comment]
Yes: http://www.smashingmagazine.com/2013/10/11/so-we-wanted-to-build-a-file-uploader-a-case-study/

**Comment by skotchio** [comment]
Is there convenient way to get base64 from either `html5 canvas` or `flash: img or div > embed` elements?

**Comment by RubaXa** [comment]
- html5: `canvas.toDataURI(...)`
- flash: Unfortunately, no way.

**Comment by skotchio** [comment]
Ok. thanks for the help.
