### ISSUE TITLE
Loaded property equals total one even if upload url returns 404 error

### ISSUE THREAD

**Issue by skotchio** [mailru/FileAPI#285]
I'm trying very basic example:

    FileAPI.upload({
      url: 'url_does_not_exists.php',
      files: { file: file },
      progress: function (e) {
        console.log(e.loaded === e.total); // true
      }                 
    });

`url_does_not_exists.php` does not exist and returns 404 error but in progress callback `e.loaded` equals `e.total` although file doesn't actually loaded to the server.

**Comment by RubaXa** [comment]
Yes, that's right, this is browser feature, and not a bug:
https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.XHR.js#L320-L322

**Comment by skotchio** [comment]
Hmm, maybe this is actually browser feature but from user's point it looks strange.

**Comment by RubaXa** [comment]
No, it does not look strange, the file is loaded, but the server did not accept him, all honest.
