### ISSUE TITLE
How to remove unnecessary post data when uploading photo?

### ISSUE THREAD

**Issue by skotchio** [mailru/FileAPI#287]
When I try to upload `image.jpg` file to the server I'm seeing the following Request Payload:

    ------WebKitFormBoundaryS1DzwmKS3K2Eey7T
    Content-Disposition: form-data; name="file"; filename="image.jpg"
    Content-Type: image/jpeg

    ------WebKitFormBoundaryS1DzwmKS3K2Eey7T
    Content-Disposition: form-data; name="_file"

    image.jpg
    ------WebKitFormBoundaryS1DzwmKS3K2Eey7T--

How to remove two latest chunks and retain Request Payload like the following? :

    ------WebKitFormBoundaryS1DzwmKS3K2Eey7T
    Content-Disposition: form-data; name="file"; filename="image.jpg"
    Content-Type: image/jpeg

    ------WebKitFormBoundaryS1DzwmKS3K2Eey7T

**Comment by RubaXa** [comment]
Do not understand the question, this part of the request and there is a file.

**Comment by skotchio** [comment]
I mean, what the following piece means?:

    ------WebKitFormBoundaryS1DzwmKS3K2Eey7T
    Content-Disposition: form-data; name="_file"

I don't set `_file` attribute but `file`:

    FileAPI.upload({
      url: './ctrl.php',
      files: { images: files },
      progress: function (evt){ /* ... */ },
      complete: function (err, xhr){ /* ... */ }
    });

**Comment by RubaXa** [comment]
No way. What is stopping you it?
