### ISSUE TITLE
Commit ae66a27223acd08f0ad5f60d broke Flash Camera

### ISSUE THREAD

**Issue by jnak** [mailru/FileAPI#289]
The Flash fallback [webcam demo](https://github.com/mailru/FileAPI/examples/webcam.html) stopped working on [commit](https://github.com/mailru/FileAPI/commit/ae66a27223acd08f0ad5f60d49938d9d03e3778c).

When I pass {html5: false, media: true}, the 'publish' method just throws an error:
- flash work: https://github.com/jnak/FileAPI/blob/flash_works/examples/webcam.html
- flash does not work: https://github.com/jnak/FileAPI/blob/flash_demo_broken/examples/webcam.html

The breaking commit is giant merge so I don't want to spend some time investigating before you guys confirm to me it is a real issue. If so, I'm happy to help :)

Awesome project btw!
Thx!

**Comment by RubaXa** [comment]
Fixed.

**Comment by jnak** [comment]
Awesome! Thanks!
