### ISSUE TITLE
Dud link

### ISSUE THREAD

**Issue by drw35** [mailru/FileAPI#291]
http://www.rubaxa.org/index.php not working.

**Comment by RubaXa** [comment]
I know :[

**Comment by drw35** [comment]
Sad times! Any fix planned?

**Comment by RubaXa** [comment]
I do not know. I do not have a server for this purpose :[

**Comment by drw35** [comment]
Ah I see! Could you post the contents of that index.php file?

**Comment by RubaXa** [comment]
https://github.com/mailru/FileAPI/blob/master/server/ctrl.php

**Comment by drw35** [comment]
Thank you!
