### ISSUE TITLE
Flash: thumbnail creation sometimes fails

### ISSUE THREAD

**Issue by jnak** [mailru/FileAPI#292]
I have a bug where an image captured with a Flash webcam generates a thumbnail fine the first time, but then fails when I try to generate another thumbnail later on.

To reproduce, run this [demo](https://github.com/jnak/FileAPI/blob/flash-timing-issue/examples/webcam.html):
1. with the console closed, when you hit 'shot', you get 2 thumbnails
2. with the console opened, when you hit 'shot', the console stops on the the 'debugger' statement. Unpause the debugger. Only one thumbnail is created. The first #get callback on line:102 never gets called.

That's the best I could do to reproduce this bug. Let me know if you need more examples.

Thanks!

**Comment by RubaXa** [comment]
Turn on `FileAPI.debug = true` and see `Console`.

**Comment by jnak** [comment]
In the demo I linked to, debug is already set to true and I don't get an error. The callback is just never called.

I've [added more logging](https://github.com/jnak/FileAPI/commit/36406de64191f15d7b3b8881de3e32ee5f86b242) to the example to better show that the callback gets called.

**Comment by jnak** [comment]
Also in a different situation (not the demo), I get this error:

```
[Log] (js -> flash).onError: TypeError: undefined is not a function (evaluating 'flash.get(id.flashId || id).cmd(name, data)') (FileAPI.js, line 345)
```

It's the issue I was originally investigating. I was trying to reproduce the same error in the demo and run into the callback issue. They're probably related.
