### ISSUE TITLE
iOS thumbnails created from Camera are wrongly rotated

### ISSUE THREAD

**Issue by jnak** [mailru/FileAPI#293]
Reproduction:
1. go to the [userpic demo](http://mailru.github.io/FileAPI/examples/userpic.html) with Safari Mobile on iOS8
2. click "browse pic", "take photo or video" (not "photo library"), and take a picture
3. The thumbnail has the wrong orientation

To make sure it was not an iOS8 bug, the twitter web mobile app lets you "take a picture" as well and the thumbnail is fine.

Let me know if I can help!
J

**Comment by RubaXa** [comment]
This is the original orientation, to rotate according to exif, you need to use:
 - Include FileAPI.exif.js
 - `FileAPI.Image(file).rotate('auto')`

**Comment by jnak** [comment]
My bad. I was running v2.0.2 because of the [Flash issue](https://github.com/mailru/FileAPI/issues/289). 

Works fine on master. Thanks for the quick response.
