### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by alanjames1987** [mailru/FileAPI#299]
This is very minor but I was wondering why this library creates the variable `FileAPI` with a capital `F`. By JavaScript convention that means that an instance of `FileAPI` can be created by using the `new` keyword, but this is not the case with `FileAPI`.

Again it's very minor but is there any reason for this?

**Comment by RubaXa** [comment]
Why not. The library is named for the technology.

Other libraries do not follow this rule:
  - jQuery — a class that begins with a lowercase letter
  - React, Backbone and etc — just an namespace
