### ISSUE TITLE
.getFiles(event) + .getInfo()

### ISSUE THREAD

**Issue by comerc** [mailru/FileAPI#300]
При вызове FileAPI.getFiles(event) наблюдается разный результат.

Если флеш включен, то внутри очевидно выполняется .getInfo(), т.к. вижу ширину-высоту в массиве info, но если через HTML5, то в результате нет массива info.

**Comment by RubaXa** [comment]
Ничего подобного, getFiles — не выолняет getInfo

**Comment by comerc** [comment]
тем не менее в FileAPI.Image присутствует массив info

**Comment by RubaXa** [comment]
А причем тут FileAPI.Image? Вы задали вопрос про getFiles, там нет вызова getInfo, в FileAPI.Image, при вызове get, есть вызов getInfo.

**Comment by comerc** [comment]
Ага, меня интересует разное поведение .get() при работе через Flash и HTML5.

Вероятно дело в этой строчке: https://github.com/mailru/FileAPI/blob/master/dist/FileAPI.js#L3741

**Comment by RubaXa** [comment]
В чем разница, приведите пример, что вы ожидали и что получили.

**Comment by comerc** [comment]
1. Вызов при работе через Flash - есть info
2. Вызов при работе через HTML5 - нет info, т.е. мне нужно проверять и вызывать .getInfo()

**Comment by RubaXa** [comment]
Я не понимаю о чем вы, приведите пример кода и что вас не устраивает.

**Comment by comerc** [comment]
```coffee
  'change input[type="file"]': (event) ->
    for inputFile in FileAPI.getFiles(event)
      Image = FileAPI.Image(inputFile)
      Image.get (error, image) ->
        console.log(Image.file.info)
```
Кстати, без разницы. При использовании Flash, я вижу info уже до вызова .get(), т.е. вот так:
```coffee
  'change input[type="file"]': (event) ->
    for inputFile in FileAPI.getFiles(event)
      Image = FileAPI.Image(inputFile)
      console.log(Image.file.info)
      Image.get (error, image) ->
```

**Comment by RubaXa** [comment]
Где вы взяли такой код? `info` можно получить только используя метод `getInfo`.

**Comment by comerc** [comment]
Вру, это так себя ведет вывод в консоль. Нужно вызвать .get(), чтобы увидеть info при использовании Flash.

**Comment by comerc** [comment]
Я же говорю, видимо дело в этой проверке: https://github.com/mailru/FileAPI/blob/master/dist/FileAPI.js#L3736

**Comment by comerc** [comment]
Пугает код примера? Это Meteor, не суть.

**Comment by RubaXa** [comment]
Давайте сначало.

1. Приведите пример кода (желательно на jsbin.com / jsfiddle.net)
2. Напишите результат его работы
3. Что в этом результате вас не устраивает

А нето вы с одного места на другое скачем, все началось с `FileAPI.getFiles`, а теперь уже `FileAPI.Image.fn.get`

P.S. Вот мой пример на jsbin http://jsbin.com/kucikakica/1/edit?html,js,output `getInfo` так, как ему пологается.
