### ISSUE TITLE
__fix_for_ie_crossdomain__

### ISSUE THREAD

**Issue by devilcoke** [mailru/FileAPI#301]
Hello, 

Somehow I'm getting 404 on fix_for_ie_crossdomain, even I got 200 for FileAPI.flash.swf and FileAPI.min.js.

Please let me know.

Thanks.

**Comment by danialfarid** [comment]
This issue is specific to angular-file-upload not FileAPI.

**Comment by danialfarid** [comment]
It is fixed at version 3.0.3 of angular file upload.
