### ISSUE TITLE
Internet Exporer 9 bug

### ISSUE THREAD

**Issue by teterovic** [mailru/FileAPI#302]
In IE9 when i click to upload a file i got this error in the console:

SCRIPT5: Access is denied.
FileAPI.min.js line 2864

the line of code is:
form.submit();

This is a security feature of IE - the file can be selected only by directly clicking on the upload. Triggering a "click" event with JavaScript will lead to the exception at the time of the upload.

http://stackoverflow.com/questions/11485096/script5-access-is-denied-in-ie9-for-iframe-on-the-same-domain...

If you set the Security Level to Low in IE, the error message will not appear on form submit.

A partial frontend back would be:
http://pritomkumar.blogspot.ch/2013/06/script5-access-denied-on-form-submit-in.html

**Comment by RubaXa** [comment]
As I understand it, the problem is no solution, besides using Flash.

**Comment by teterovic** [comment]
It's more a front end problem when you don't directly press the upload button but try to trigger it manually with javascript.

One solution is to warn the developer/user (try-catch block) or to try to simulate it using an iframe

**Comment by RubaXa** [comment]
It is only to suppress the error, but does not solve the problem.

**Comment by RubaXa** [comment]
I added a `try/catch` in [hostfixes](https://github.com/mailru/FileAPI/tree/hotfixes)-branch (not know how it will help you)
