### ISSUE TITLE
File upload with crop not working on firefox and ie

### ISSUE THREAD

**Issue by blackat13** [mailru/FileAPI#305]
I'm using file api indicated here http://rubaxa.github.io/jquery.fileapi/
I pushing the images into hull.io storage services. debugged all around and I tracked it back to file api, what I'm doing is having the user upload an image then giving him an option to crop. this works on chrome but not on firefox and ie. it has the same image parameters passed into the upload function for both chrome and firefox. 

https://hellocubee-staging.squarespace.com/assets/FileAPI_HULL-crop-upload-image/index.html

he is the sample html file with the code.

**Comment by LukeAbell** [comment]
+1 on this, anyone?

**Comment by RubaXa** [comment]
https://github.com/RubaXa/jquery.fileapi#warnign-this-plugin-is-not-maintained
