### ISSUE TITLE
Can not work on IE9

### ISSUE THREAD

**Issue by grace-liujing** [mailru/FileAPI#306]
Hi, I want to run the get started example on IE9, but it failed. I consoled the result, it said evt is empty.(var files = FileAPI.getFiles(evt);) and files are empty ( var files = FileAPI.getFiles(evt);) Could you tell me how to resolve it? thank you.

**Comment by RubaXa** [comment]
Please check:
1. `Flash` support (http://mailru.github.io/FileAPI/#en/FileAPI.support.flash)
2. `js-fileapi-wrapper` required class name (http://mailru.github.io/FileAPI/#en/buttons.examples)
3. If that does did not help, turn on `FileAPI.debug = true` and see `Console`.
