### ISSUE TITLE
При использовании библиотеки на домене .рф в Firefox (MacOS) выдается ошибка

### ISSUE THREAD

**Issue by dmitrys99** [mailru/FileAPI#307]
В консоли:
renderImageToCanvas failed
FileAPI.js (строка 343)
[err] FileAPI.Image.fn._apply
Object:
columnNumber 0
data null
filename "http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js"
inner null
lineNumber 2260
message ""
name "NS_ERROR_NOT_AVAILABLE"
result 2147746065

Stack: 
"api.renderImageToCanvas@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:2260:10 Image.prototype._apply@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1956:0 Image.prototype._trans/<@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:2075:6 Image.prototype._load/<@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1898:5 _emit@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1480:2 api.readAsImage@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:724:6 api.readAsImage@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:745:5 api.readAsImage@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:705:7 Image.prototype._load@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1897:4 Image.prototype._trans@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:2069:3 Image.prototype.get@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:2097:5 init/</Shdmka.setUpUpload/</</<@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/shdmka.js:235:16 _each@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:168:7 init/</Shdmka.setUpUpload/</<@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/shdmka.js:232:14 _next@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1008:7 _next/<@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1004:8 _next@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:942:7 _next/<@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:933:10 api.defer/defer.resolve@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:464:8 @http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/plugins/FileAPI.exif.js:59:4 _emit@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1480:2 _fn@http://ÑÐ´Ð¼ÐºÐ°.ÑÑ/st/js/dist/FileAPI.js:1504:5 "

К сведению: домен шдмка.рф. В Сафари и Хроме на макос работает корректно.

**Comment by RubaXa** [comment]
И? Это вам всё же в баг трекер мозилы, я тут ничего поделать не могу.

**Comment by dmitrys99** [comment]
Да, похоже что FF дает пустую картинку в блобе для кирилличного домена.
Может быть в этом случае принудительно переключиться во Flash? И можно ли это вообще сделать?

**Comment by RubaXa** [comment]
Можете принудительно переключить:
```js
var FileAPI = {
   html5: false
};
```

**Comment by dmitrys99** [comment]
Превью заработало, спасибо.
Для загрузки, видимо, нужно возвращать 200 ответ?

**Comment by dmitrys99** [comment]
Не получается у меня побороть загрузку. Превью работает, но отправка не работает.
Пришлось изменить логику работы и сделать без превью вообще.
Настройка crossdomain.xml не помогла (или я что-то делаю не так).

**Comment by dmitrys99** [comment]
Похоже, решение все же нашлось.

Если заменить строку apiURL = (window.createObjectURL && window) || (window.URL && URL.revokeObjectURL && URL) || (window.webkitURL && webkitURL),
на apiURL = false, то превью в html режиме работает корректно, т.е. если мы исключаем использование createObjectURL, то создание картинки из блоба работает.

Можно, в принципе, кейс закрывать.
