### ISSUE TITLE
Preview an image file thumbnail, just that

### ISSUE THREAD

**Issue by masbicudo** [mailru/FileAPI#310]
I'm trying to preview an image file, but without uploading it to `ctrl.php`... just select a file and preview it, and let the browser upload the file when the user hits submit. Is it possible? Could you guide me in doing so?

**Comment by malinin13** [comment]
Take a look at this.
http://rubaxa.github.io/jquery.fileapi/

**Comment by RubaXa** [comment]
- http://mailru.github.io/FileAPI/examples/thumbnails.html
 - http://mailru.github.io/FileAPI/examples/caman.html

**Comment by RubaXa** [comment]
In all the examples image thumbnail build without the participation of the server.
