### ISSUE TITLE
Upload больших файлов в IE приводит к ошибке "Arithmetic result exceeded 32 bits"

### ISSUE THREAD

**Issue by Octane** [mailru/FileAPI#311]
В IE есть лимит на размер загружаемого файла: [File Upload and Download Limits](http://blogs.msdn.com/b/ieinternals/archive/2011/03/10/wininet-internet-explorer-file-download-and-upload-maximum-size-limits.aspx)

Если попытаться отправить через FileAPI большой файл, например 28ГБ, то метод `xhr.send(form)`  (строка [#1089](https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.core.js#L1089)) выкинет exception, которое не будет поймано и ни один из колбеков не выполнится.

-----
UPD: ошибка происходит при добавлении файла в инстанс FormData [#137](https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.Form.js#L137)

**Comment by RubaXa** [comment]
@Octane т.е. тут только `try catch`?

**Comment by Octane** [comment]
Как вариант можно проверять 
```js
upload: function (options){
    …
    if (isNativeFormData && !options.chunkSize && file.size > MAX_FILE_SIZE) {
        …complete(new TypeError('Arithmetic result exceeded 32 bits'));
    } else {
        // Start upload
        xhr.send(form);
    }
   …
}
```
где `MAX_FILE_SIZE` устанавливается в зависимости от браузера, но наверное лучше `try-catch`

**Comment by RubaXa** [comment]
Да, лучше `try catch`, стабильнее это.

**Comment by Octane** [comment]
https://github.com/mailru/FileAPI/pull/315
