### ISSUE TITLE
getDropFiles: возвращать массив c неудачно прочтенными файлами и папками

### ISSUE THREAD

**Issue by Octane** [mailru/FileAPI#318]
Так как остается не решенной проблема в OS X с именами папок в формате Unicode NFD (#314, #317), необходима возможность оповестить пользователя о том, какие файлы и папки не будут загружены.

Предлагаю такое API:
```js
FileAPI.getDropFiles(function (files, all) {
    
    var failed = all.filter(function (anything) {
        return anything.error;
    });

    failed[0].name // 'йод'
    failed[0].error.message // 'The URL is malformed. Make sure that the URL is complete and valid'

});
```

**Comment by RubaXa** [comment]
Согласен.

**Comment by RubaXa** [comment]
@Octane Кстати, ты у хрома задача есть по этому поводу? Если есть, приложи ссылку, если нет, надо им написать.

**Comment by Octane** [comment]
@RubaXa, не нашел ничего похожего в issues на googlecode. Напишу.

**Comment by Octane** [comment]
[Issue 473618](https://code.google.com/p/chromium/issues/detail?id=473618)

**Comment by RubaXa** [comment]
О, круто! Надеюсь они без примера не пошлют, а то могу гады.

**Comment by Octane** [comment]
https://github.com/mailru/FileAPI/pull/321
