### ISSUE TITLE
IE9 Does not return File Size in object

### ISSUE THREAD

**Issue by LiamChapman** [mailru/FileAPI#323]
I'm trying to filter the file size in IE9. But it appears to not be in the object.

I'm using something like this:

FileAPI.filterFiles(files, function (file, info) {
 if (file.size < 10 * FileAPI.MB) return true;
});

When I log the file object it only has the following items in IE9:

- name
- type
- blob
- iframe

Does it not support size? When I print file.size it returns NaN due to it not being set.

Thanks,

**Comment by RubaXa** [comment]
Please check:
1. `Flash` support (http://mailru.github.io/FileAPI/#en/FileAPI.support.flash)
2. `js-fileapi-wrapper` required class name (http://mailru.github.io/FileAPI/#en/buttons.examples)
3. If that does did not help, turn on `FileAPI.debug = true` and see `Console`.

**Comment by LiamChapman** [comment]
Thanks for the speedy reply. I have got debugging enabled and I get the values mentioned in my previous post. I have the required class name in place too. Everything works perfectly, but I can't get File Size in IE. I'll take a look at the flash support.

**Comment by LiamChapman** [comment]
I've had a play with some of the settings and I can't get the file size to return in IE 9.

It seems to be ok in IE10, IE11 and other browsers. Is there something I'm missing?

This is the code I'm using to upload and manage my image file.

```
// Upload File Button
self.uploadPhoto = function (evt) {
	var input  = document.getElementById('photo-file');
	var files = FileAPI.getFiles(evt);
	if (files.length > 0) {
		FileAPI.filterFiles(files, function (file, info) {
			// file type
			if( /^image/.test(file.type) ){
				// file size set to 10mb
				if (file.size < 10 * FileAPI.MB) {
					return true;
				} else {
					// tracking						
					self.errorPrompt('File size is too large.');
				}
				// return true;
			} else {
				self.errorPrompt('Images Only.');
			}				
			return false;
		}, function (files, rejected) {						
			FileAPI.each(files, function (file) {
                FileAPI.Image(file).rotate('auto').get(function (err, img) {                        	
                	// FileAPI.getInfo(file, function (err, info) {
                	// 	console.log(info);
                	// });
                	// Uploading Files
					FileAPI.upload({
						url: '/media/lib/FileAPI/server/ctrl.php',
						files: { images: file },
						imageAutoOrientation: true,
						imageOriginal: false,
						imageTransform: {
							maxWidth: globalWidth * 2
						},
						complete: function (err, xhr) { 
							var data  = JSON.parse(xhr.responseText);
							var image = data.images.images;
							// process image
							processUploadedImage(image);
						}
					});	//end FileAPI upload
                });//end FileAPI Image
            });// end FileAPI Each.                    
		}); //end filterFiles
	}//endif files
};
```

**Comment by RubaXa** [comment]
If that does did not help, turn on `FileAPI.debug = true` and copy-paste `Console`.

**Comment by LiamChapman** [comment]
On Load it logs this:

With File Size Detection On:

```
LOG: FlashAPI.state: awaiting 
LOG: (flash -> js).log: storeKey=509060501205072735307293030729_2.0.10 
LOG: (flash -> js).log: timeout=0 
LOG: FlashAPI.state: ready 
```

With the file size dectection off it returns this:

```
LOG: FileAPI: 2.0.10 
LOG: protocol: http: 
LOG: doctype: [html] null null 
LOG: meta.http-equiv: IE=edge 
LOG: FlashAPI.state: awaiting 
LOG: (flash -> js).log: storeKey=509060501205072735307293030729_2.0.10 
LOG: (flash -> js).log: timeout=0 
LOG: FlashAPI.state: ready 
LOG: FlashAPI.Image._load: [object Object] 
LOG: FileAPI.Form.toHtmlData 
LOG: XHR._send: [object DocumentFragment] 
LOG: <form style="top: -1000px; width: 1px; height: 1px; overflow: hidden; position: absolute;" encType="multipart/form-data" method="POST" action="/media/lib/FileAPI/server/ctrl.php?fileapi14286593151489" target="fileapi14286593151487"><iframe onload="window.fileapi14286593151487Load &amp;&amp; fileapi14286593151487Load();" src="javascript:false;" name="fileapi14286593151487"></iframe><input name="callback" value="fileapi14286593151487" type="hidden"><input id="photo-file" name="images" value="" accept="image/*" type="file" capture="camera"></form> 
LOG: xhr.end: 200 OK 
```

Could be that I have to wrap my filter in the FileAPI.upload() method?

Thanks.

**Comment by RubaXa** [comment]
According to the log you have not added class `js-fileapi-wrapper`

**Comment by LiamChapman** [comment]
My HTML for is the following:

```
<div class="js-fileapi-wrapper">
	<form enctype="multipart/form-data">
		<label for="photo-file" id="photo-file-label">
			<input type="file" name="photo-file" id="photo-file" accept="image/*" capture="camera" value="">
			<span class="btn upload-photo-btn">Upload</span>
		</label>
	</form>
</div>
```

It works perfectly in all browsers. The only thing is that in IE9 it does not return the file.size in the object. If I disable the file.size it works ok in IE9. Surely it's a bug with file.size in IE9?

**Comment by LiamChapman** [comment]
When I log file.size. It returns NaN

**Comment by RubaXa** [comment]
This can be any problems with the layout, the library does not see the class `js-fileapi-wrapper`

**Comment by RubaXa** [comment]
Create an example on jsbin.com

**Comment by LiamChapman** [comment]
OK. But it sees it when I don't have the following block of code:

```
// file size set to 10mb
if (file.size < 10 * FileAPI.MB) {
    return true;
} else {
    // tracking                     
    self.errorPrompt('File size is too large.');
}
```

I'll try and make a JSBin example.. 

Thanks.

**Comment by LiamChapman** [comment]
I've created a JSBIN here..

http://jsbin.com/sacimapayi/1/edit?js,console,output

However it the console on load it returns this error:

""Unable to get value of the property 'on': object is null or undefined (line 1)"

But that also happens in a example you created a while ago here 
http://jsbin.com/kucikakica/1/edit?html,js,console,output 
(via https://github.com/mailru/FileAPI/issues/300#issuecomment-72629337)

In chrome both work.

**Comment by RubaXa** [comment]
Your example is working:

```
LOG: FileAPI: 2.0.10 
LOG: protocol: http: 
LOG: doctype: [html] null null 
LOG: meta.http-equiv: IE=edge,chrome=1 
LOG: FlashAPI.state: awaiting 
LOG: (flash -> js).log: storeKey=5090615022050727353072930307296040_2.0.10 
LOG: (flash -> js).log: timeout=0 
LOG: FlashAPI.state: ready 
LOG: FlashAPI.event.mouseenter: [object Object] 
LOG: (js -> flash).multiple: false 
LOG: (flash -> js).log: parseCmd, command: multiple 
LOG: (js -> flash).accept: art,bm,bmp,dwg,dxf,cbr,cbz,fif,fpx,gif,ico,iefs,jfif,jpe,jpeg,jpg,jps,jut,mcf,nap,nif,pbm,pcx,pgm,pict,pm,png,pnm,qif,qtif,ras,rast,rf,rp,svf,tga,tif,tiff,xbm,xpm,xwd,ART,BM,BMP,DWG,DXF,CBR,CBZ,FIF,FPX,GIF,ICO,IEFS,JFIF,JPE,JPEG,JPG,JPS,JUT,MCF,NAP,NIF,PBM,PCX,PGM,PICT,PM,PNG,PNM,QIF,QTIF,RAS,RAST,RF,RP,SVF,TGA,TIF,TIFF,XBM,XPM,XWD 
LOG: (flash -> js).log: parseCmd, command: accept 
```


Most likely the problem is in your CSS.

**Comment by RubaXa** [comment]
```html
<div class="js-fileapi-wrapper">
		<form enctype="multipart/form-data">
			<label for="photo-file" id="photo-file-label">
				<input type="file" name="photo-file" id="photo-file" accept="image/*" capture="camera" value="">
				<span class="btn upload-photo-btn">Upload</span>
			</label>
		</form>
	</div>
	<script>
		FileAPI.event.on(document.getElementById('photo-file'), 'change', function (evt) {
			alert(FileAPI.getFiles(evt)[0].size);
		});
	</script>
```

![Alert](https://dl.dropbox.com/s/7mudj7lmyxpuell/Screenshot%202015-04-10%2013.52.04.png?dl=0)

**Comment by LiamChapman** [comment]
hmm ok. I'll take a look and see what I find. Thanks for taking a look into this.

**Comment by LiamChapman** [comment]
I removed my css and I appears you are right. It's something to do with it. It successfully logs the file size and other bits of data. Thanks for helping me pinpoint the issue. 

Is there a reason why it could be the CSS? Have you come across any specific causes or reasons as to why it might occur? I don't think I have any thing major that I think would cause it. I hide then show the element. Could be something like that?

**Comment by LiamChapman** [comment]
OK, found it. It's because I had the input set to display none. (I trigger the click via the label). I'll need to think of something else to do something similar.

Thanks a lot for all your help. Hopefully this issue will help someone else in the future if they come across it.

**Comment by sunilhari** [comment]
I am facing a similar problem.After reading this post i had removed display none from my input element.Even then it is not returning the size in  IE9
