### ISSUE TITLE
Win10. Spartan. Drag'n'Drop — does not work.

### ISSUE THREAD

**Issue by RubaXa** [mailru/FileAPI#334]
> Попробовал страничку mailru.github.io/FileAPI/examples/demo.html в win10 Spartan project.
> Не работает DnD.
> Устарела demo-страничка или пока что еще есть проблемы у FileAPI с этим браузером?

@Octane Вы ещё не проверяли в Spartan?

**Comment by Octane** [comment]
@RubaXa, смотрел, не работает DnD, но насколько я понял он нигде не работает, даже в OneDrive…
