### ISSUE TITLE
FileAPI.each с break и continue

### ISSUE THREAD

**Issue by bIbI4k0** [mailru/FileAPI#340]
Возможно ли внедрить функционал each, аналогичный jQuery:

Если callback-функция возвращает false, это прерывает обход коллекции( то есть, эмуляция break, как в обычных циклах). Иначе, если функция возвращает значение, отличное от false - это аналогично continue.

**Comment by RubaXa** [comment]
Увы, не могу этого сделать, это сломает обратную совместимость.
