### ISSUE TITLE
Files inside "dist" for release 2.0.13 say they are 2.0.11

### ISSUE THREAD

**Issue by Kirkis** [mailru/FileAPI#345]
Hi,

The title says it all. It is also the case with release 2.0.12.
Also, when I diff most files inside "dist" folder for v2.0.13 against v2.0.11, there is no change.

Both zip and targz are affected:
https://github.com/mailru/FileAPI/archive/2.0.12.zip
https://github.com/mailru/FileAPI/archive/2.0.12.tar.gz
https://github.com/mailru/FileAPI/archive/2.0.13.zip
https://github.com/mailru/FileAPI/archive/2.0.13.tar.gz

Regards,

**Comment by RubaXa** [comment]
That's right, changes have occurred into the Flash-part:
- FileAPI-2.0.12/dist/FileAPI.flash.swf    37 338 bytes (2015/08/28)
- FileAPI-2.0.13/dist/FileAPI.flash.swf    37 469 bytes (2015/08/31)

**Comment by Kirkis** [comment]
What I meant was, when opening the .js files provided in the release, their source code says the files are v2.0.11 not v2.0.13, which can be confusing when looking at a consumer project to identify outdated libs.

**Comment by RubaXa** [comment]
Да, это маленькая оплошность.

**Comment by RubaXa** [comment]
Yes, it is a small mistake.

**Comment by Kirkis** [comment]
Just to confirm that it looks good in v2.0.15.
Thanks!
