### ISSUE TITLE
debug mode crashes on console.log.apply in IE8

### ISSUE THREAD

**Issue by mlarcher** [mailru/FileAPI#353]
When debug: true is set in the config object, IE8 crashes on `if( console.log.apply ){` with the following error: `Object doesn't support this action`. Would it be possible to make sure the console is available before trying to use it ?

**Comment by RubaXa** [comment]
And there is: https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.core.js#L252-L259

**Comment by mlarcher** [comment]
Hm... right. Well it seemsIE8 still chokes on the test.
Here is a few relevant tests and their output:
`alert(console)` -> `[object Object]`
`alert('typeof console')` -> `object`
`alert(console.log)` -> `[object]`
`alert('typeof console.log')` -> `object`
`alert('typeof {}')` -> `object`
`alert('({}).apply')` -> `undefined`
`alert('typeof console.log.apply')` -> `unknown`
`alert('console.log.apply')` -> Error thrown: "Object doesn't support this action"

For some reason, IE8 returns a type "unknown" instead of "function" and crashes when we try to evaluate the expression. The typeof check itself doesn't seem to be an issue for it, so would it be possible to have `if( typeof console.log.apply === 'function' ){` instead of `if( console.log.apply ){` ?
related infos: http://stackoverflow.com/questions/10982739/typeof-returning-unknown-in-ie

**Comment by RubaXa** [comment]
Try hotfixes-branch: https://github.com/mailru/FileAPI/commit/963ab1ca5629fddab15c289df356078ac1a53b17

**Comment by mlarcher** [comment]
Looks good to me. No more crashing.

**Comment by mlarcher** [comment]
@RubaXa any ETA for when this will land in a stable release ?

**Comment by RubaXa** [comment]
Done.

**Comment by mlarcher** [comment]
Thanks. I guess we can close the issue now.
