### ISSUE TITLE
FileAPI.upload отправка всех файлов одним запросом

### ISSUE THREAD

**Issue by evrikaart** [mailru/FileAPI#354]
Добрый день!
У функции FileAPI.upload есть возможность отправить массив файлов одним запросом (непоследовательно)? 
Если нет, планируется ли такая доработка?

**Comment by RubaXa** [comment]
Планировалось, даже реализовано в dev-ветке, но dev-ветка не будет включена никогда, увы.

**Comment by evrikaart** [comment]
Увы.
Спасибо за быстрый ответ!
