### ISSUE TITLE
FileAPI.filterFiles - after first error resolved by first reader, filtering ends

### ISSUE THREAD

**Issue by LukasRada** [mailru/FileAPI#358]
Before invoking FileAPI.filterFiles I have defined two info readers:
1. default image info reader - /dist/FileAPI.html5.js
2. exif info reader - /plugins/FileAPI.exif.js

When the first one is finished in error, no chance to test get file info by the second info reader is given.

Here is image for repro: http://1drv.ms/1LPYCYu

**Comment by RubaXa** [comment]
Yes it is.

**Comment by LukasRada** [comment]
And why is API rely only on the first (default) reader? When I skip the first info reader (because of unrecognizing repro image), then the exif info reader recognize the repro image.

Do you think that this is correct behavior? //Somehow, I'm guessing your answer :)

**Comment by RubaXa** [comment]
Difficult question and "yes" and "no", but "no" outweighed.
