### ISSUE TITLE
setting content-disposition to attachment in multi-part form

### ISSUE THREAD

**Issue by grahamlittle** [mailru/FileAPI#360]
i am just wondering if it is possible to set the content-disposition to attachment where the part in the Multi-Part-form is a file. I think after looking at the code that it currently isn't. Line 2735 in FileAPI.js is set to the following: 

```js     
       '--_' + boundary + ('\r\nContent-Disposition: form-data; name="'+ file.name +'"'+ (file.file ? '; filename="'+ encodeURIComponent(file.file) +'"' : '')
```

I notice there are already a number of checks to see if the part of the multi-part-form is a file or not so would it be valid/possible to add a check for content disposition as well?

something like instead:

```js
       (file.file) ? '\r\nContent-Disposition: attachment;' : '\r\nContent-Disposition: form-data;';
```

Maybe my question is not valid and all parts of multi-part form-data should set content-disposition to form-data, but i appreciate your comments/help anyway. i have a related question in if anyone wants to look at samples: http://stackoverflow.com/questions/33753440/content-disposition-with-ng-file-upload-and-angularjs

**Comment by RubaXa** [comment]
I'm sorry, but I do not understand the question, try rephrasing it and more detail describe your problem.

**Comment by grahamlittle** [comment]
@RubaXa sorry i submitted the comment before finishing the typing should be full comment now

**Comment by RubaXa** [comment]
Still do not understand. The current implementation corresponds to browser, here is an example:
http://jsbin.com/kekuxovuxu/edit?html,output

```
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarySnlMl8XxjFid2iFA

Request Payload
------WebKitFormBoundarySnlMl8XxjFid2iFA
Content-Disposition: form-data; name="foo"

bar
------WebKitFormBoundarySnlMl8XxjFid2iFA
Content-Disposition: form-data; name="file"; filename="augustusgaiusoctavius.png"
Content-Type: image/png

------WebKitFormBoundarySnlMl8XxjFid2iFA--
```

**Comment by grahamlittle** [comment]
@RubaXa What i would like to see is:

Content-Type:multipart/form-data; boundary=----WebKitFormBoundarySnlMl8XxjFid2iFA

Request Payload
------WebKitFormBoundarySnlMl8XxjFid2iFA
Content-Disposition: form-data; name="foo"

bar
------WebKitFormBoundarySnlMl8XxjFid2iFA
Content-Disposition: attachment; name="file"; filename="augustusgaiusoctavius.png"
Content-Type: image/png

------WebKitFormBoundarySnlMl8XxjFid2iFA--

**Comment by RubaXa** [comment]
That is wrong, in rfc well defined what kind headers need to set: https://www.ietf.org/rfc/rfc1867.txt
Search `Form-based File Upload in HTML`

**Comment by grahamlittle** [comment]
@RubaXa yes it looks like your right about that, i guess that will be a no on the change then ;o) The reason i was asking for this is because on the server side apache-camel is closing the stream because content-disposition is set to form-data and not attachment for the files. I will see if they can fill me in on why this is the case. 

Thank you very much for your time and help

**Comment by grahamlittle** [comment]
@RubaXa i had a further look at the spec you provided and its a bit confusing to me because i have noticed that in the examples section not only is content-disposition=form-data valid but also content-disposition=attachment here is the segment:

 Suppose the server supplies the following HTML:

     <FORM ACTION="http://server.dom/cgi/handle"
           ENCTYPE="multipart/form-data"
           METHOD=POST>
     What is your name? <INPUT TYPE=TEXT NAME=submitter>
     What files are you sending? <INPUT TYPE=FILE NAME=pics>
     </FORM>

   and the user types "Joe Blow" in the name field, and selects a text
   file "file1.txt" for the answer to 'What files are you sending?'

   The client might send back the following data:

        Content-type: multipart/form-data, boundary=AaB03x

        --AaB03x
        content-disposition: form-data; name="field1"

        Joe Blow
        --AaB03x
        content-disposition: form-data; name="pics"; filename="file1.txt"
        Content-Type: text/plain

         ... contents of file1.txt ...
        --AaB03x--

   If the user also indicated an image file "file2.gif" for the answer
   to 'What files are you sending?', the client might client might send
   back the following data:

        Content-type: multipart/form-data, boundary=AaB03x

        --AaB03x
        content-disposition: form-data; name="field1"

        Joe Blow
        --AaB03x
        content-disposition: form-data; name="pics"
        Content-type: multipart/mixed, boundary=BbC04y

        --BbC04y
        Content-disposition: attachment; filename="file1.txt"



Nebel & Masinter              Experimental                      [Page 9]

RFC 1867             Form-based File Upload in HTML        November 1995


        Content-Type: text/plain

        ... contents of file1.txt ...
        --BbC04y
        Content-disposition: attachment; filename="file2.gif"
        Content-type: image/gif
        Content-Transfer-Encoding: binary

          ...contents of file2.gif...
        --BbC04y--
        --AaB03x--

**Comment by RubaXa** [comment]
Opportunity is there, but it is a special case, File API mimics the behavior of the browser.
In addition, the code to which you are referring, is executed only for the old FireFox < 4 and Opera < 12.
The behavior should be the same, so now the right multipart forms.

**Comment by grahamlittle** [comment]
@RubaXa ok i understand, thanks for your time again
