### ISSUE TITLE
Has problem implementing "paste to upload"

### ISSUE THREAD

**Issue by jiyinyiyong** [mailru/FileAPI#363]
Here's my current work around:
https://github.com/teambition/react-lite-uploader/blob/master/src/app/upload-area.coffee#L51

```coffee
  onPaste: (event) ->
    clipboardData = event.clipboardData
    accept = @props.accept.split(',')
    .map (extension) -> extension.slice(1)

    Array::forEach.call clipboardData.types, (type, i) =>
      if type is 'Files'
        matchFile = accept.some (extension) ->
          fileType = clipboardData.items[i].type
          fileType.indexOf(extension) >= 0
        if matchFile
          pastedFileName = 'pasted'
          # Blob to File http://stackoverflow.com/q/27159179/883571
          file = new File [clipboardData.items[i].getAsFile()], pastedFileName
          @uploadFile file
```

There's a problem, `uploadFile` checks its arguments and need it to be created by `File` constructor. However, `window.File` is not implemented in old browsers as told in http://caniuse.com/#search=File .

I tried to cheat the API by creating my own `File` from the `Blob` returned by `paste` event, but it can not be cheated according to the code:

https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.core.js#L476
```js
			isFile: function (file){
				return _toString.call(file) === '[object File]';
			},
```

Any idea to make pasting work?

Updated: well, MDN says `File` is supported since IE10, https://developer.mozilla.org/en-US/docs/Web/API/File#Browser_compatibility That's different from what caniuse said.

**Comment by RubaXa** [comment]
1. [getAsFile](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFile) already returns File.

2. 
> I tried to cheat the API by creating my own File from the Blob returned by paste event

Give an example of the code as you did this.

**Comment by jiyinyiyong** [comment]
As I `console.log`ed the result of `getAsFile`, it was a `Blob`, not a `File`.

And I tried this code and then found it not recognised as a `File`:
http://stackoverflow.com/a/29390393/883571

```js
function blobToFile(theBlob, fileName){
    //A Blob() is almost a File() - it's just missing the two properties below which we will add
    theBlob.lastModifiedDate = new Date();
    theBlob.name = fileName;
    return theBlob;
}
```

I may add details(screenshots) later when I start working on that part in our project.

**Comment by RubaXa** [comment]
Oh, sure!

**Comment by RubaXa** [comment]
@jiyinyiyong try hotfixes-branch.

**Comment by jiyinyiyong** [comment]
It's quick. I think this code works now :)
![image](https://cloud.githubusercontent.com/assets/449224/12049097/f89972ba-af1d-11e5-89f4-f08eb7b39a5a.png)

**Comment by RubaXa** [comment]
Stop, Wait a minute. I did not understand how to hinders the function `isFile`? Method `FileAPI.upload` is able to upload `Blob`.

**Comment by jiyinyiyong** [comment]
http://qnimate.com/an-introduction-to-javascript-blobs-and-file-interface/

> #### File Interface
> A File object in JavaScript references an actual file in the local filesystem. This File object inherits all properties and methods from the Blob class. Although the File objects and Blob objects are different, they expose same methods and properties.

**Comment by RubaXa** [comment]
This is understandable, but how it relates to `isFile`?
Once again, this library is able to work with the `Blob`.

**Comment by jiyinyiyong** [comment]
My mistake, it was not happening during uploading, but during the time I was trying to render that image:

https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.core.js#L616

![image](https://cloud.githubusercontent.com/assets/449224/12049311/7c70f5fc-af20-11e5-8bd9-ae53d4eeef4c.png)

**Comment by RubaXa** [comment]
О! Try https://github.com/mailru/FileAPI/blob/hotfixes/lib/FileAPI.core.js#L616

**Comment by jiyinyiyong** [comment]
It works.

I think it should be `isFile(file) || isBlob(file)`. Files from dropping pass `File` and files from pasting pass `Blob`.

**Comment by RubaXa** [comment]
Just `isBlob(file)`: https://github.com/mailru/FileAPI/blob/hotfixes/lib/FileAPI.core.js#L486-L488

**Comment by jiyinyiyong** [comment]
Just found that :)

**Comment by TyGuy1016** [comment]
Guys, I put that file up a long time ago, (or did I?) I was just kinda using Github as a online file hosting thing. Just to store that file. I am a beginner at code, heck, the stopwatch html page, I had to get my friend to write that for me! I don't understand the code in this, i am deleting it.

**Comment by jiyinyiyong** [comment]
Will this change be merged into master?

**Comment by RubaXa** [comment]
Today or tomorrow.

**Comment by RubaXa** [comment]
@jiyinyiyong + fileapi@2.0.18

**Comment by jiyinyiyong** [comment]
Thanks!
