### ISSUE TITLE
Camera#stop — does not work.

### ISSUE THREAD

**Issue by Connormiha** [mailru/FileAPI#364]
## Camera.stop работает не корректно. Видео ставится на паузу, но камера по прежнему включена(горит лампочка).

Вот вот этом месте:
```javascript
/**
* Stop camera streaming
*/
stop: function (){
	try {
		this._active = false;
		this.video.pause();
		this.stream.stop();
	} catch( err ){ }
},
```
Если убрать try catch, на строчке `this.stream.stop();` вылезет ошибка `this.stream.stop is not a function`
Воспроизводиться в последних Firefox, Chrome.
В том числе можно увидеть на официальном демо: https://mailru.github.io/FileAPI/examples/webcam.html

**Comment by RubaXa** [comment]
Починил, ветка hotfixes

**Comment by RubaXa** [comment]
@Connormiha если всё ок, я релизну, а то уже много задач висит.

**Comment by Connormiha** [comment]
@RubaXa подтверждаю, после этого фикса проблемы больше нет.
