### ISSUE TITLE
About size field in FormData

### ISSUE THREAD

**Issue by jiyinyiyong** [mailru/FileAPI#365]
We run into a problem and located it at:
```js
Form.append(name, file, filename);
```
https://github.com/mailru/FileAPI/blob/master/lib/FileAPI.core.js#L1333

The server requests a `size` field in order to handle large files properly:

```js
Form.append('size', file.size);
Form.append(name, file, filename);
```

In order to fix this problem, we need to added `size` field in every upload request. FileAPI seems don't have such an options, is it OK to put `size` in every request then?

**Comment by RubaXa** [comment]
Use https://github.com/mailru/FileAPI#preparefunction

**Comment by jiyinyiyong** [comment]
Found the solution! I should have saw it.

Thanks.
