### ISSUE TITLE
issue with large files more than 2Mb

### ISSUE THREAD

**Issue by anushkadar** [mailru/FileAPI#374]
when i am trying to upload image larger than 2MB not receiving expected parameters in server side.
Below is the result I got for large file.
Array
(    [filedata] => Array
        (
            [name] => 047_WOA_003.jpg
            [type] => 
            [tmp_name] => 
            [error] => 1
            [size] => 0
        ))

Here is the script I used
<script>
jQuery(function ($){
$('#simple-btn').fileapi({
   url: '../server/ctrl.php',
   multiple: true,
   maxSize: 50 * FileAPI.MB,
   autoUpload: true,
   elements: {
      size: '.js-size',
      active: { show: '.js-upload', hide: '.js-browse' },
      progress: '.js-progress'
   }
});
});

Small files working fine without no issues.
version FileAPI-2.0.20
browsers chorme Version 48.0.2564.109 m, 
firefox 45.0.1

**Comment by RubaXa** [comment]
http://php.net/manual/en/features.file-upload.errors.php

**Comment by anushkadar** [comment]
Thanks a lot. I have confused with post_max_size, (I am new to PHP),
