### ISSUE TITLE
Additional post data which is dynamic wont send as it change (Help needed)

### ISSUE THREAD

**Issue by anushkadar** [mailru/FileAPI#375]
I am trying to send additional post data which is pic_count, but always received the same value even my debug shows it has changed.
please help to figure out this

$('#multiupload').fileapi({
		multiple: true,
		autoUpload: true,
		maxFiles : maxfiles,
		data : {'pic_count' : count++},

**Comment by RubaXa** [comment]
Alas, I cannot help, jquery.fileapi is not maintained.
