### ISSUE TITLE
FileAPI.min.js:2891 Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by DollBin** [mailru/FileAPI#380]
I get the follow error:
FileAPI.min.js:2891 Uncaught TypeError: Cannot read property 'indexOf' of undefined

This is a url variable is undefined.

**Comment by RubaXa** [comment]
Please check:
1. `Flash` support (http://mailru.github.io/FileAPI/#en/FileAPI.support.flash)
2. `js-fileapi-wrapper` required class name (http://mailru.github.io/FileAPI/#en/buttons.examples)
3. If that does did not help, turn on `FileAPI.debug = true` and see `Console`.

**Comment by DollBin** [comment]
It seems the follow code is not contain url param.

                options = _extend({
                    jsonp: 'callback'
                    , prepare: api.F
                    , beforeupload: api.F
                    , upload: api.F
                    , fileupload: api.F
                    , fileprogress: api.F
                    , filecomplete: api.F
                    , progress: api.F
                    , complete: api.F
                    , pause: api.F
                    , imageOriginal: true
                    , chunkSize: api.chunkSize
                    , chunkUploadRetry: api.chunkUploadRetry
                    , uploadRetry: api.uploadRetry
                }, options);

**Comment by RubaXa** [comment]
Again!

Please check:
1. `Flash` support (http://mailru.github.io/FileAPI/#en/FileAPI.support.flash)
2. `js-fileapi-wrapper` required class name (http://mailru.github.io/FileAPI/#en/buttons.examples)
3. If that does did not help, turn on `FileAPI.debug = true` and see `Console`.
