### ISSUE TITLE
How can I upload files at one http request?

### ISSUE THREAD

**Issue by wangcansunking** [mailru/FileAPI#386]
Since the backend interface only supports accepting all files at once, So how can I update the configuration to use FileAPI.upload to upload files at one http request.
NOT one file one request!

anyone knows?

Best regards!

**Comment by wangcansunking** [comment]
@RubaXa

**Comment by im-saxo** [comment]
You can upload one image in several sizes at one multipart request, but as far as I know uploading several different files at one request is not supported

**Comment by RubaXa** [comment]
Yes, no such possibility.
