### ISSUE TITLE
Can I disable the Flash parts of FileAPI?

### ISSUE THREAD

**Issue by kajmagnus** [mailru/FileAPI#390]
I don't want FileAPI use Flash or send an extra request to the server for `flash.swf`.

Here: https://github.com/mailru/FileAPI#flash I don't see any `enabled: true/false` option

(I don't support old browsers anyway in my app.)

(B.t.w. thanks for making & publishing FileAPI, I find it very useful.)

**Comment by Bertg** [comment]
Same here, I'd rather something fails, then have the code fall back (or attempt to load) flash.

**Comment by RubaXa** [comment]
Only using html5 assembly.

**Comment by Bertg** [comment]
Hi @RubaXa , thx for the quick response  got it. 

However using it as a dev in webpack made this slightly more challenging. For people getting here using FileAPI in web pack, you can use the following config snippet to use the html5 package.

```js
var path = require('path');
var root = path.normalize(path.join(__dirname, '../', '../'));

module.exports = {
  resolve: {
    alias: {
      'fileapi': path.join(root, 'node_modules', 'fileapi', 'dist', 'FileAPI.html5.js')
    }
  }
}
```

Your setup might be different, so don't blindly copy/paste.

**Comment by kajmagnus** [comment]
And in my case I changed from:

```
      'node_modules/fileapi/dist/FileAPI.js',
```

to:

```
      'node_modules/fileapi/dist/FileAPI.html5.js', // don't use the Flash version (w/o '.html5')
```

Closing this issue then
