### ISSUE TITLE
Flashvar callback not triggered

### ISSUE THREAD

**Issue by leandroz** [mailru/FileAPI#394]
While developing locally its working ok, but once I deploy to the server the callback never gets triggered, no issues in the logs.

<param name="flashvars" value="callback=FileAPI.Flash.onEvent&amp;flashId=fileapi14872960440692&amp;storeKey=50101235373656029248753736_2.0.7&amp;timeout=0&amp;debug=1">

It happens in Chrome, IE9 , Safari.

**Comment by im-saxo** [comment]
Probably wrong allowScriptAccess parameter?

**Comment by leandroz** [comment]
The problem was the mimeType in the server wasnt correct when delivering the flash file.
