### ISSUE TITLE
ZLIB на клиенте

### ISSUE THREAD

**Issue by mihdan** [mailru/FileAPI#397]
Реально ли прикрутить библиотеку [pako](https://github.com/nodeca/pako), например, чтобы упаковать изображения в ZIP до их отправки на сервер. Если да, то в какую сторону копать?

**Comment by RubaXa** [comment]
Есть одна недокументированная возможность, можно передать в upload произвольный `Blob`:

```js
FileAPI.upload({
   files: {
     'photo': {
         file: 'filename.ext',
         blob: myBlobData,
     }
   }
})
```

**Comment by mihdan** [comment]
Это бомба. Спасибо, Константин за проделанную вами работу - это великолепный проект

**Comment by arusakov** [comment]
@mihdan 
Вообще архивировать изображения - не самая тру идея, потому что изображения в jpg/png итак очень сильно сжаты, zip их делает больше, а не меньше.

**Comment by mihdan** [comment]
Ни разу не видел, чтобы в зипе было что-то больше, чем без него о_О

**Comment by RubaXa** [comment]
Потому что они уже сжаты тем или иным алгоритмом, кроме это изображения обладают высокой энтропией.

**Comment by arusakov** [comment]
Если хочется ускорить загрузку, то можно на клиенте резать файл на куски и загружать их параллельно на сервер

**Comment by mihdan** [comment]
Спасибо за совет, так и поступим, хотя погоняю еще и зип

**Comment by mihdan** [comment]
В песочнице [pako](http://codepen.io/Bombasarkadian/full/RKgXQx/) любой закинутый мною файл уменьшаяет почти в 2 раза - так вроде как уменьшаяется файл

**Comment by theKashey** [comment]
@mihdan - если бы zip жал бы изображения - то все изображения хранились бы в зипе. К сожалению как zip не может сжать zip - так он не сможет сжать и изображение.
Максимум заголовки, но потом своих добавит.

**Comment by mihdan** [comment]
Я понял, что это бестолковая затея. Вопрос: почему тогда существуют подобные библиотеки, позиционирующие себя как упаковщик именно изображений? Про текстовые файлы понятно.

**Comment by arusakov** [comment]
@mihdan 
Я знаю, что существуют несколько достаточно известных библиотек, которые не пакуют, а уменьшают размер изображения на клиенте (было 5000х5000, стало 1000х1000) и вот такую уменьшенную фотографию уже отсылают на сервер. Это действительно ускоряет загрузку и действительно уменьшает размер файла (значительно), но вы теряете в качестве. Но для большинства сервисов это не критично, поэтому это отличный способ переложить немного логики с сервака на клиент.

**Comment by RubaXa** [comment]
Кстати да, в FileAPI реализация сжатия почти без хитростей, так что если нужно что-то серьезнее, лучше использовать pica.

**Comment by mihdan** [comment]
Спасибо за пояснения
ср, 5 апр. 2017 г. в 12:09, Lebedev Konstantin <notifications@github.com>:
