### ISSUE TITLE
Не показывает прогресс загрузки каждого файла

### ISSUE THREAD

**Issue by SlimSavernake** [mailru/FileAPI#408]
Когда выбираю один файл, прогрессбар уходит сразу на 100%. Если, например, выбрать 4 одинаковых файла то прогресс будет увеличиваться сразу на 25% с загрузкой каждого файла, а не по чуть-чуть.
То есть я не вижу процесс загрузки каждого файла.
Пожалуйста покажите мне правильный код на основе моего примера, где видно прогресс загрузки каждого файла.
Вот мой код:
```
var choose = document.getElementById('choose');
FileAPI.event.on(choose, 'change', function (evt){

    var files = FileAPI.getFiles(evt); // Retrieve file list

    FileAPI.filterFiles(files, function (file, info){
        if( /^image/.test(file.type) ){
            return  info.width >= 320 && info.height >= 240;
        }
        return  false;
    }, function (files){
        if( files.length ){

            // Загружаем файлы
            FileAPI.upload({
                url: '/photo/default/upload',
                files: { images: files },
                progress: function (evt){
                    $('.js-fileapi-progress').css('width', evt.loaded/evt.total*100+'%');
                },
            });
        }
    });
});
```

**Comment by RubaXa** [comment]
Варинта тут два
1. Нет поддержки HTML5 или Flash
2. У вас быстрое соединение

Включите дебаг режим, станет понятнее что происходит.

**Comment by SlimSavernake** [comment]
Спасибо за быстрый ответ. Проверял только на локальном сервере, значит все-таки причина в быстром соединении.
