### ISSUE TITLE
readas* in IE7 and IE8

### ISSUE THREAD

**Issue by dcarricajo** [mailru/FileAPI#415]
I need file contens in Javascript for that version of IE. Any chance?
Thanks in advance

**Comment by RubaXa** [comment]
![image](https://user-images.githubusercontent.com/1109562/47371125-eb6b3680-d6ef-11e8-8a95-4162ed4d70fb.png)

✅ https://github.com/mailru/FileAPI#readasdataurlfileobject-callbackfunctionvoid
⚠️ https://github.com/mailru/FileAPI#flash
