### ISSUE TITLE
Моки FileAPI.XHR для тестирования

### ISSUE THREAD

**Issue by ogonkov** [mailru/FileAPI#422]
А есть уже моки для `FileAPI.XHR`? Там используется собственная обёртка над сабмитом формы вместо `XMLHttpRequest`, библиотеки типа `jasmine-ajax` не подходят.

**Comment by RubaXa** [comment]
Увы, моков нет.

**Comment by ogonkov** [comment]
Примечание по поводу тестирования, если кто-то наткнётся на этот тред.

В замыкании сохраняется ссылка на оргинальный объект `XMLHttpRequest`, поэтому библиотеки типа `jasmine-ajax` не будут работать, нужно вручную подменять объект xhr.

```js
import FileAPI from 'fileapi';

beforeEach(function() {
  jasmine.Ajax.install();

  spyOn(FileAPI, 'getXHR').and.callFake(function() {
    return new window.XMLHttpRequest();
  });
});

afterEach(function() {
  jasmine.Ajax.uninstall();
});

**Comment by ogonkov** [comment]
Кроме этого, если мокается `setTimeout`, то нужно вызывать `tick(0)` после запроса и после ответа, т. к. в методах разбросаны вызовы `setTimeout`.

```js
beforeEach(function() {
  jasmine.clock().install();
});

afterEach(function() {
  jasmine.clock().uninstall();
});

it('...', function() {
  this.model.save();

  jasmine.clock().tick(0);

  const request = jasmine.Ajax.requests.mostRecent();

  request.respondWith(mockSuccessResponse);

  jasmine.clock().tick(0);
});
```
