### ISSUE TITLE
rotate + overlay = issue (overlay isn't displayed)

### ISSUE THREAD

**Issue by RomainMazB** [mailru/FileAPI#427]
Hi.

I tried to rotate an image and then overlay a watermark image.

Didn't know why my code don't work until I tried to modify the FileAPI official example to add .rotate.

You can see the result on [this fiddle](https://jsfiddle.net/RomainMazB/bxkfqe37/) : it doesn't work, watermark isn't applied.

The only thing I changed from the [original script](http://mailru.github.io/FileAPI/examples/watermark.html) is the line 174 in my fiddle: I just added .rotate(90) execution.

A solution for that?

**Comment by RomainMazB** [comment]
I found the problem ans suggest a pull request.

Hope this helps :)

**Comment by RubaXa** [comment]
Thx a lot!

**Comment by RubaXa** [comment]
Merged!
